-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 08:38:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chat_client
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chat_client
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat_client` DEFAULT CHARACTER SET utf8 ;
USE `chat_client` ;

-- -----------------------------------------------------
-- Table `chat_client`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_client`.`Users` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `chat_client`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_client`.`Messages` (
  `message_id` INT NOT NULL,
  `message` TEXT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`message_id`));


-- -----------------------------------------------------
-- Table `chat_client`.`Message_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_client`.`Message_Users` (
  `message_id` INT NOT NULL,
  `from_id` INT NOT NULL,
  `to_id` INT NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `user_id_fk_idx` (`from_id` ASC) VISIBLE,
  INDEX `to_user_id_fk_idx` (`to_id` ASC) VISIBLE,
  CONSTRAINT `from_user_id_fk`
    FOREIGN KEY (`from_id`)
    REFERENCES `chat_client`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `to_user_id_fk`
    FOREIGN KEY (`to_id`)
    REFERENCES `chat_client`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `message_id_fk`
    FOREIGN KEY ()
    REFERENCES `chat_client`.`Messages` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `chat_client`.`User_Connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_client`.`User_Connections` (
  `user_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  INDEX `friend_id_fk_idx` (`friend_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `friend_id`),
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `chat_client`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `friend_id_fk`
    FOREIGN KEY (`friend_id`)
    REFERENCES `chat_client`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
