-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 08:10:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `mydb`.`Messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Messages` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Messages` (
  `message_id` INT NOT NULL,
  `message` TEXT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`message_id`));


-- -----------------------------------------------------
-- Table `mydb`.`Message_Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Message_Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Message_Users` (
  `message_id` INT NOT NULL,
  `from_id` INT NOT NULL,
  `to_id` INT NOT NULL,
  PRIMARY KEY (`message_id`, `from_id`, `to_id`),
  CONSTRAINT `from_user_id_fk`
    FOREIGN KEY (`from_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `to_user_id_fk`
    FOREIGN KEY (`to_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `message_id_fk`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Messages` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `user_id_fk_idx` ON `mydb`.`Message_Users` (`from_id` ASC) VISIBLE;

CREATE INDEX `to_user_id_fk_idx` ON `mydb`.`Message_Users` (`to_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
