"""Run the same queries on SQLite and PostgreSQL and compare what comes back.

    pip install "psycopg[binary]"
    python demo.py                                   # SQLite in memory + local Postgres
    PG_URL=postgresql://me:pw@host/db python demo.py # some other Postgres

Everything is created as a TEMP table, so nothing is left behind in either
database. If PostgreSQL isn't reachable, the SQLite half still runs.
"""

from __future__ import annotations

import os

from dbrun import Database

PG_URL = os.environ.get("PG_URL", "postgresql://student:student@localhost:5432/course")

# The one thing we can't share: DDL. The types are spelled the same, but they
# MEAN different things (SQLite: suggestions; PostgreSQL: enforced).
CREATE = {
    "sqlite": """
        CREATE TEMP TABLE purchases (
            purchase_id   INTEGER PRIMARY KEY,         -- alias for rowid
            customer_id   INTEGER NOT NULL,
            department    TEXT    NOT NULL,
            amount        NUMERIC NOT NULL,            -- stored as a float
            purchase_date TEXT    NOT NULL             -- ISO-8601 text
        )""",
    "postgres": """
        CREATE TEMP TABLE purchases (
            purchase_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_id   integer       NOT NULL,
            department    text          NOT NULL,
            amount        numeric(10,2) NOT NULL,      -- exact decimal
            purchase_date date          NOT NULL
        )""",
}

ROWS = [
    {"cust": 1, "dept": "Games", "amount": 19.99, "day": "2026-01-15"},
    {"cust": 1, "dept": "Games", "amount": 0.10, "day": "2026-01-16"},
    {"cust": 1, "dept": "Books", "amount": 0.20, "day": "2026-02-01"},
    {"cust": 2, "dept": "Garden", "amount": 45.00, "day": "2026-02-03"},
]

# Everything below is written ONCE, SQLite-style, and runs on both.
INSERT = """
    INSERT INTO purchases (customer_id, department, amount, purchase_date)
    VALUES (:cust, :dept, :amount, :day)
"""

BY_CUSTOMER = """
    SELECT customer_id, COUNT(*) AS n, SUM(amount) AS total
    FROM purchases
    WHERE customer_id = :cust
    GROUP BY customer_id
"""

# A literal % in a LIKE pattern AND a :named parameter in the same query --
# the case that breaks a naive search-and-replace.
LIKE_AND_PARAM = """
    SELECT department, amount FROM purchases
    WHERE department LIKE 'G%' AND amount > :min
    ORDER BY amount
"""

# Portable SQL that still behaves differently: 'games' vs 'Games'.
CASE_TEST = "SELECT COUNT(*) AS n FROM purchases WHERE department LIKE 'games'"


def show(title: str, value) -> None:
    print(f"  {title:<28} {value}")


def demo(db: Database) -> None:
    print(f"\n=== {db!r} ===")
    db.execute(CREATE[db.kind])

    with db.transaction():
        db.execute_many(INSERT, ROWS)

    # RETURNING works on both (SQLite 3.35+).
    new = db.query_one(INSERT.strip() + " RETURNING purchase_id", ROWS[0])
    show("new purchase_id", new)

    # query_one() may return None, so when we index the row right away we use
    # query()[0] instead -- a list, never None, which keeps the type checker happy.
    row = db.query(BY_CUSTOMER, {"cust": 1})[0]
    show("customer 1 totals", row)
    show("type(total)", type(row["total"]).__name__)

    day = db.query("SELECT purchase_date FROM purchases LIMIT 1")[0]["purchase_date"]
    show("type(purchase_date)", f"{type(day).__name__}  {day!r}")

    show("LIKE 'G%' AND amount > 1", db.query(LIKE_AND_PARAM, {"min": 1}))
    show("LIKE 'games' matches", db.query(CASE_TEST)[0]["n"])

    # A failed transaction leaves nothing behind -- on both.
    before = db.query("SELECT COUNT(*) AS n FROM purchases")[0]["n"]
    try:
        with db.transaction():
            db.execute(INSERT, ROWS[0])
            db.execute(INSERT, {**ROWS[0], "cust": None})   # NOT NULL violation
    except db.IntegrityError as exc:
        show("IntegrityError caught", type(exc).__name__)
    after = db.query("SELECT COUNT(*) AS n FROM purchases")[0]["n"]
    show("rows before / after", f"{before} / {after}  (rolled back)")

    print("  plan:")
    for line in db.explain(BY_CUSTOMER, {"cust": 1}):
        print("     ", line)


def main() -> None:
    with Database("sqlite:///:memory:") as db:
        demo(db)
    try:
        with Database(PG_URL) as db:
            demo(db)
    except Exception as exc:   # no server, no psycopg, bad password, ...
        print(f"\n(skipping PostgreSQL: {type(exc).__name__}: {exc})")


if __name__ == "__main__":
    main()
