// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 16
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){





var Ga=this,Ha=function(){var a=YT.Player,b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},Ja=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ka=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,La=function(a){if(null==a)return String(a);var b=Ka.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ma=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},qa=function(a){if(!a||"object"!=La(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ma(a,"constructor")&&!Ma(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ma(a,b)},Na=function(a,b){var c=b||("array"==La(a)?[]:{}),d;for(d in a)if(Ma(a,d)){var e=a[d];"array"==La(e)?("array"!=La(c[d])&&(c[d]=[]),c[d]=Na(e,c[d])):qa(e)?(qa(c[d])||(c[d]={}),c[d]=Na(e,c[d])):c[d]=e}return c};var ua=null,Oa=Math.random(),Pa=null,Qa=null,Ca=!1,Ra={},Sa={},Da={};var Ta,Ua,Va,Xa,Ya,Za,$a,ab,bb,cb,db,eb,R,fb,gb,hb,ib,jb,kb,lb,mb,ob,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Lb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,S,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,pd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,
ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf;
(function(){var a=function(a){return{toString:function(){return a}}};Ta=a("");Ua=a("0");Va="";Xa=a("");Ya=a("");Za=a("");$a=a("");ab=a("");bb=a("");cb=a("");db=a("");eb=a("3");R=a("4");fb=a("");gb=a("");hb=a("");
ib=a("");jb=a("");kb=a("");lb=a("");mb=a("");ob=a("");qb=a("");rb=a("");sb=a("");tb=a("");ub=a("");vb=a("");wb=a("");xb=a("");
yb=a("");zb=a("");Ab=a("5");Bb=a("");Cb=a("");Db=a("");Eb=a("6");Fb=a("");Gb=a("");Hb=a("");Ib=a("");Jb=a("");Lb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");
Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("7");Yb=a("");Zb=a("8");$b=a("");ac=a("");bc=a("9");cc=a("");dc=a("");ec=a("10");fc=a("");gc=a("");
hc=a("");ic=a("");jc=a("");kc=a("11");lc=a("");mc=a("12");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");sc=a("");tc=a("");vc=a("13");wc=a("");xc=a("");
yc=a("14");zc=a("15");Ac=a("16");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("");Jc=a("17");Kc=a("");Lc=a("30");Mc=a("31");Nc=a("");Oc=a("");
Pc=a("18");S=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("19");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("");ed=a("20");fd=a("");gd=a("");
hd=a("");id=a("");jd=a("");kd=a("");ld=a("");md=a("");pd=a("");sd=a("");td=a("21");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("22");zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");
Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");
Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");me=a("");
ne=a("24");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");
Ee=a("25");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le="";Me=a("");Ne=a("26");Oe=a("");Pe=a("");Qe=a("");Re=a("27");Se=a("");Te=a("");Ue=a("");
Ve=a("");We=a("");Xe=a("");Ye=a("");Ze=a("");$e=a("28");af=a("29");bf=a("")})();var cf=function(){},M=function(a){return"function"==typeof a},df=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},ef=function(a){return"number"==La(a)&&!isNaN(a)},ff=function(a){return/^[0-9]+$/.test(a)},gf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},hf=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},P=function(a){return Math.round(Number(a))||0},ma=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},jf=function(a){var b=[];if(df(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},G=function(){return new Date},kf=function(a,b){if(!ef(a)||!ef(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},lf=function(){this.prefix="gtm.";this.values={}};lf.prototype.set=function(a,b){this.values[this.prefix+a]=b};lf.prototype.get=function(a){return this.values[this.prefix+a]};lf.prototype.contains=function(a){return void 0!==this.get(a)};
var mf=function(a,b,c){try{if(!a[jd])return a[Jc](a,b||cf,c||cf);c&&c()}catch(d){}return!1},nf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=hf(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},of=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},pf=function(a){return function(){return a("GTM-K7KZWM")}},qf=function(a){for(var b=0;b<a.length;b++)a[b]()},rf=G().getTime(),pa=function(){return"gtm"+
rf++},ra=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},sf=function(a,b,c){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=c},tf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},uf=function(a,b){0==b?a.Ua=!0:a.complete=!0;var c=a.g;a.s&&(a.s.Fa[c]=b);Ra[c]&&(Ra[c].state=b)},vf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var v=window,J=document,Ef=navigator,O=function(a,b,c){var d=v[a];v[a]=void 0===d||c?b:d;return v[a]},I=function(a,b,c,d){return(d||"http:"!=v.location.protocol?a:b)+c},Ff=function(a){var b=J.getElementsByTagName("script")[0]||J.body||J.head;b.parentNode.insertBefore(a,b)},ta=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},q=function(a,b,c){var d=J.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;ta(d,b);c&&(d.onerror=c);Ff(d);return d},ga=function(a,b){var c=J.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Ff(c);ta(c,b);void 0!==a&&(c.src=a);return c},D=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},U=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},B=function(a){v.setTimeout(a,
0)},xa=!1,ya=[],Gf=function(a){if(!xa){var b=J.createEventObject,c="complete"==J.readyState,d="interactive"==J.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){xa=!0;for(var e=0;e<ya.length;e++)ya[e]()}ya.push=function(){for(var a=0;a<arguments.length;a++)B(arguments[a]);return 0}}},Hf=0,If=function(){if(!xa&&140>Hf){Hf++;try{J.documentElement.doScroll("left"),Gf()}catch(a){v.setTimeout(If,50)}}},Kf=function(a){var b=J.getElementById(a);if(b&&Jf(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Jf(document.all[a][c],
"id")==a)return document.all[a][c];return b},Jf=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Lf=function(a){return a.target||a.srcElement||{}},Ba=function(a){var b=J.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Mf=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&
(e=null);return e},Nf=!1,Of=[],Pf=function(){if(!Nf){Nf=!0;for(var a=0;a<Of.length;a++)Of[a]()}},Qf=function(a){a=a||v;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},za=function(a){window.console&&window.console.log&&window.console.log(a)};var aa=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||v.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||v.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:v.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=gf(d||[],k[k.length-
1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),l=0;l<m.length;l++){var p=m[l].split("=");if(decodeURIComponent(p[0]).replace(/\+/g," ")==e){f=decodeURIComponent(p.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Rf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},ba=function(a){var b=J.createElement("a");
a&&(b.href=a);return b};var ia=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var fa=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=aa(ba(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},ka=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};var Sf=new lf,Tf={},Vf={set:function(a,b){Na(Uf(a,b),Tf)},get:function(a){return N(a,2)},reset:function(){Sf=new lf;Tf={}}},N=function(a,b){if(2==b){for(var c=Tf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Sf.get(a)},Uf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Wf=Math.random(),Xf="1.000000">Wf;var Yf=cf;var Zf=cf,$f=[],ag=!1,ca=function(a){return v["dataLayer"].push(a)},bg=function(a){var b=!1;return function(){!b&&M(a)&&B(pf(a));b=!0}},hg=function(){for(var a=!1;!ag&&0<$f.length;){ag=!0;var b=$f.shift();if(M(b))try{b.call(Vf)}catch(va){}else if(df(b))a:{var c=b;if("string"==La(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Tf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(va){}}}else{var k=b,m=void 0;for(m in k)if(k.hasOwnProperty(m)){var l=m,
p=k[m];Sf.set(l,p);Na(Uf(l,p),Tf)}var r=!1,u=k.event,w=void 0;if(u){w=rf++;Qa=u;if(!k["gtm.uniqueEventId"]){var x=w;Sf.set("gtm.uniqueEventId",x);Na(Uf("gtm.uniqueEventId",x),Tf)}var z=bg(k.eventCallback),E=k.eventTimeout;E&&v.setTimeout(z,Number(E));r=Zf(w,u,z,k.eventReporter)}Pa||(Pa=k["gtm.start"])&&Yf();var H=k,F=w,y=u,K=Tf;if(!r){var C=w,L=u;
}Qa=null;a=r||a}var T=b,Q=Tf;gg();ag=!1}return!a},ig=function(){var a=hg();try{var b=v["dataLayer"].hide;if(b&&void 0!==b["GTM-K7KZWM"]&&b.end){b["GTM-K7KZWM"]=!1;var c=!0,d;for(d in b)if(!0===b[d]){c=!1;break}c&&(b.end(),
b.end=null)}}catch(e){}return a};var Fa=function(a,b){U(a,"load",b,void 0)},ea=function(a,b,c){q(a,b,c)},Ea=function(a,b){v[a]=b},n=function(a,b,c){var d=v;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},t=function(a,b,c){return("https:"==v.location.protocol?a:b)+c};var jg=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),kg={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},lg={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},mg=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},ng=function(){var a=N("gtm.whitelist");
var b=a&&mg(jf(a),kg),c=N("gtm.blacklist")||N("tagTypeBlacklist")||[];jg.test(v.location&&v.location.hostname)&&(c=jf(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&mg(jf(c),lg),e={};return function(f){var g=f&&f[Jc];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>gf(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>gf(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(c){var l;if(!(l=0<=gf(d,g.a)))a:{for(var p=g.b||[],r=new lf,u=0;u<d.length;u++)r.set(d[u],!0);for(u=0;u<p.length;u++)if(r.get(p[u])){l=!0;break a}l=!1}m=l}return e[g.a]=!h||m}};var wf=function(a){var b=J;return og?b.querySelectorAll(a):null},pg=!1;if(J.querySelectorAll)try{var qg=J.querySelectorAll(":root");qg&&1==qg.length&&qg[0]==J.documentElement&&(pg=!0)}catch(a){}var og=pg;var _eu=function(a){var b=String(N("gtm.elementUrl")||a[ec]||""),c=ba(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Qa};_e.a="e";_e.b=["google"];var vg=/(^|\.)doubleclick\.net$/i,wg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,oa=function(a){for(var b=String(J.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=hf(e[0]);if(f&&f==a){var g=hf(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},xg=function(a,b,c,d,e){if(vg.test(J.location.hostname)||"/"==c&&wg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=J.cookie;J.cookie=f;return g!=
J.cookie||0<=gf(oa(a),b)},yg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},zg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},Ag=function(){var a=aa(v.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var Bg=function(a,b){this.f=a;this.j=b};Bg.prototype.toString=function(){var a=""+this.f;1<this.j&&(a=a+"-"+this.j);return a};var Cg=function(a,b){this.Da=a;this.ea=b};Cg.prototype.toString=function(){return""+this.ea+"."+this.Da};var Fg=function(a,b){var c=new Dg(null,a,b);Eg(c);return c},Dg=function(a,b,c){this.La=Math.floor(G().getTime()/864E5);this.da=b||"auto";this.W=c||"/";var d=yg(this.da),e=zg(this.W);this.F=a||new Bg(d,e);this.h=[];this.C=new lf},Hg=function(a,b,c){b&&(""==c.Da?Gg(a,b):(a.C.contains(b)||a.h.push(b),a.C.set(b,c)))},Ig=function(a,b){for(var c=0;c<b.length;c++)Hg(a,b[c][0],b[c][1])},Gg=function(a,b){var c=gf(a.h,b);0<=c&&a.h.splice(c,1);a.C.set(b,void 0)},Jg=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.C.get(d)])}return b},Kg=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.C.get(a.h[c]).ea);return 864E5*b};Dg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.C.get(c).toString())}return"GAX1."+this.F.toString()+"."+a.join("!")};
var Lg=function(a,b){for(var c=new Date,d=zg(a.W),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.C.get(g).ea<a.La&&e.push(g)}for(f=0;f<e.length;f++)Gg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(Kg(a));if("auto"!=a.da)return xg("_gaexp",a.toString(),a.W,a.da,c);for(var h=Ag(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.F=new Bg(yg(h[k]),d),xg("_gaexp",a.toString(),a.W,h[k],c)))return!0;return!1},Eg=function(a){for(var b=a.F.f,c=a.F.j,d=oa("_gaexp"),e=[],f=0;f<d.length;f++){var g=Mg(a,d[f]);g&&e.push(g)}vf(e,
function(a,d){var e=a.F,f=d.F;return e.f==f.f&&e.j==f.j?!1:e.f==b&&e.j==c?!0:f.f==b&&f.j==c?!1:e.f==b?f.f!=b||e.j<f.j:f.f==b?!1:e.j==c?f.f!=b&&(f.j!=c||e.f<f.f):f.j==c?!1:e.f<f.f||e.f==f.f&&e.j<f.j});a.F=0<e.length?e[0].F:new Bg(b,c);for(f=e.length-1;0<=f;f--)Ig(a,Jg(e[f]))},Mg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=hf(e[0]);if(0!=f.length){var g=2==e.length?hf(e[1]):"1";if(ff(f)&&ff(g)){d=new Bg(P(f),P(g));
break a}}}d=void 0}if(d){for(var h=new Dg(d,a.da,a.W),k=(c[2]||"").split("!"),m=0;m<k.length;m++){var l=k[m].split(".");if(3==l.length){if(!ff(l[1]))return;Hg(h,l[0],new Cg(l[2],P(l[1])))}}return h}}};var _v=function(a){var b=N(a[td].replace(/\\\./g,"."),a[Xb]);return void 0!==b?b:a[ec]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(N("gtm.referrer")||J.referrer);if(!b)return b;var c=ba(b);return b};_f.a="f";_f.b=["google"];var ja=function(a){var b=v.location,c;(c=a[Ub]?a[Ub]:N("gtm.url"))&&(b=ba(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Eb]&&(f=aa(b,a[Eb],a[he],a[dc],a[Vd]));return f},_u=ja;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a[eb]).indexOf(String(a[R]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a[eb])==String(a[R])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a[R],a[Qc]?"i":void 0)).test(a[eb])};_re.a="re";_re.b=["google"];var $g,ah,bh,ch=/(Firefox\D28\D)/g.test(Ef.userAgent),ih=function(a,b){return function(c){c=c||v.event;var d=Lf(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Mf(d,["a","area"]),e=!d||!d.href||dh(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?bh:ah;if(c.defaultPrevented||!1===c.returnValue||c.ra&&c.ra()){if(d){var g={simulateDefault:!1},h=eh(f,["wnc","nwnc"]);h&&fh(a,d,g,f.wt,h)}}else{if(d){var g={},k,m=eh(f,
["wnc","nwnc","nwc","wc"]);(k=fh(a,d,g,f.wt,m))||(gh(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&ch;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=hh(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},fh=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Jf(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=jh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=kh(b);g.eventTimeout=f;g.eventCallback=lh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return ca(g)},
kh=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},mh=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},hh=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Ef.userAgent),e=mh(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=v.frames&&v.frames[f]||v[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+G().getTime(),b.targetWindow=v.open("",b.targetWindowName));break;default:d&&!v.frames[e]?(b.simulateDefault=!1,c=!0):(v.frames[e]||(b.targetWindowName=e),b.targetWindow=v.frames[e]||v.open("",e))}return c},jh=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||G().getTime(),500>G().getTime()-c&&v.setTimeout(jh(a,b,c),25)))}},lh=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);J.gtmSubmitFormNow=!0;nh(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||G().getTime(),500>G().getTime()-c&&v.setTimeout(lh(a,b,c),25)}},eh=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},oh=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},gh=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<ph.length;c++)if(a.passingRules[c]){var d=qh[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=ph[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},rh=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(J.gtmHasClickListenerTag)return;J.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Lf(a);b&&fh("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!$g&&($g=Rf(J.location));oh(ah,b||!1,c||!1,d,e);if(J.gtmHasLinkClickListenerTag)return;
J.gtmHasLinkClickListenerTag=!0;f="click";g=ih(a,b||!1);break;case "FORM_SUBMIT":oh(bh,b||!1,c||!1,d,e);if(J.gtmHasFormSubmitListenerTag)return;J.gtmHasFormSubmitListenerTag=!0;f="submit";g=ih(a,b||!1);break;default:return}U(J,f,g,h)},dh=function(a){if(!$g)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ba(a);return $g==Rf(c)},nh=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
J.gtmFormElementSubmitter||(J.gtmFormElementSubmitter=J.createElement("form"));return J.gtmFormElementSubmitter.submit.call?J.gtmFormElementSubmitter.submit:a.submit};var Ng=new String("undefined"),zh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Ng?b:a[d]);return c.join("")}};zh.prototype.toString=function(){return this.resolve("undefined")};zh.prototype.valueOf=zh.prototype.toString;var Ah={},Bh=function(a,b){var c=rf++;Ah[c]=[a,b];return c},Ch=function(a){var b=a?0:1;return function(a){var c=Ah[a];if(c&&M(c[b]))c[b]();Ah[a]=void 0}};var Dh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Eh=function(a,b){return a<b?-1:a>b?1:0};var Fh;a:{var Gh=Ga.navigator;if(Gh){var Hh=Gh.userAgent;if(Hh){Fh=Hh;break a}}Fh=""}var W=function(a){return-1!=Fh.indexOf(a)};var Ih=function(a){Ih[" "](a);return a};Ih[" "]=function(){};var Kh=function(a,b){var c=Jh;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Lh=W("Opera"),Mh=W("Trident")||W("MSIE"),Nh=W("Edge"),Oh;if(Oh=W("Gecko"))Oh=!(-1!=Fh.toLowerCase().indexOf("webkit")&&!W("Edge"));var Ph=Oh&&!(W("Trident")||W("MSIE"))&&!W("Edge"),Qh=-1!=Fh.toLowerCase().indexOf("webkit")&&!W("Edge");Qh&&W("Mobile");W("Macintosh");W("Windows");W("Linux")||W("CrOS");var Rh=Ga.navigator||null;Rh&&(Rh.appVersion||"").indexOf("X11");W("Android");!W("iPhone")||W("iPod")||W("iPad");W("iPad");W("iPod");
var Sh=function(){var a=Ga.document;return a?a.documentMode:void 0},Th;a:{var Uh="",Vh=function(){var a=Fh;if(Ph)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Nh)return/Edge\/([\d\.]+)/.exec(a);if(Mh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Qh)return/WebKit\/(\S+)/.exec(a);if(Lh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Vh&&(Uh=Vh?Vh[1]:"");if(Mh){var Wh=Sh();if(null!=Wh&&Wh>parseFloat(Uh)){Th=String(Wh);break a}}Th=Uh}
var Xh=Th,Jh={},Yh=function(a){return Kh(a,function(){for(var b=0,c=Dh(String(Xh)).split("."),d=Dh(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],m=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==m[0].length)break;b=Eh(0==k[1].length?0:parseInt(k[1],10),0==m[1].length?0:parseInt(m[1],10))||Eh(0==k[2].length,0==m[2].length)||Eh(k[2],m[2]);g=k[3];h=m[3]}while(0==b)}return 0<=b})},Zh;
var $h=Ga.document;Zh=$h&&Mh?Sh()||("CSS1Compat"==$h.compatMode?parseInt(Xh,10):5):void 0;var ai;if(!(ai=!Ph&&!Mh)){var bi;if(bi=Mh)bi=9<=Number(Zh);ai=bi}ai||Ph&&Yh("1.9.1");Mh&&Yh("9");var Aa=function(a,b){var c="";Mh&&!ci(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(di)a.srcdoc=d;else if(ei){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else fi(a,d)},di=Qh&&"srcdoc"in document.createElement("iframe"),ei=Ph||Qh||Mh&&Yh(11),fi=function(a,b){Mh&&Yh(7)&&!Yh(10)&&6>gi()&&hi(b)&&(b=ii(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};Mh&&!ci(a)?ji(a,c):c()},gi=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},ci=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Ih(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},ki=0,ji=function(a,b){var c="goog_rendering_callback"+ki++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},hi=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},ii=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var mi=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=mi(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=J.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,ta(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);mi(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(m){B(d)}}};var oi=function(a,b,c){if(J.body){var d=
a[Pc];d instanceof zh&&(d=d.resolve(Bh(b,c)),b=cf);if(a[Se])try{Aa(ga(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),B(b)}catch(e){B(c)}else a[Ue]?ni(d,b,c):mi(J.body,Ba(d),b,c)()}else v.setTimeout(function(){oi(a,b,c)},200)},_html=oi;_html.a="html";_html.b=["customScripts"];
var Ai=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=xi(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var k=yi(a+"{"+e+"}",f);zi(k,f);var m=k.parentNode;return function(){m.removeChild(k)}},Bi=null,xi=function(a){if(Bi)return Bi;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return Bi=c}0==a.styleSheets.length&&
a.createStyleSheet();return Bi=a.styleSheets[0]},yi=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},zi=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var Ii={},Ji=void 0,Ki=function(a){var b=Ii[a];b||(b={id:a,v:[],T:0,Ga:null,xa:void 0,Ba:!1},Ii[a]=b);Ji=b},Mi=function(a,b,c,d){var e=Ji;if(!og||!e)return!1;var f={id:e.id+":"+e.v.length,cb:b,R:[],Ya:c,G:a,pa:0,na:d||null,Ka:0,S:!1};e.v.push(f);null===a?(f.S=!0,b(null)):Li(e);return!0},Ni=function(a){var b=Ai(a,"visibility","hidden",!0);return function(){M(b)&&b.apply();b=null}},Oi=function(a,b,c,d){var e=b;if(!xa){var f=Ni(a.A);ya.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Mi(a,e,
c,d)},Li=function(a){if(!a.Ba){for(var b=a.T;b<a.v.length;b++){var c=a.v[b],d=b==a.T;if(!c.S&&!Pi(d,c))break;c.S&&d&&a.T++}a.v.length>a.T?(a.Ga||(a.Ga=v.setTimeout(function(){a.Ga=null;Li(a)},80)),xa||a.xa||(a.xa=function(){B(function(){Li(a)})},U(J,"DOMContentLoaded",a.xa))):Qi(a)}},Qi=function(a){for(var b=0;b<a.v.length;b++){var c=a.v[b];if(c.G)for(var d=wf(c.G.A)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Ri(f,c.id),c.R.push(Si(f,c.id)))}}},Pi=
function(a,b){var c=[];if(b.G){var d=Ti(b.G,b.id),e=null;b.na&&(e=Ti(b.na,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!xa&&(null===b.na.o||b.Ka+c.length<b.na.o)))break;c.push({element:g,Hb:h})}}if(!xa&&b.Ya&&(!a||null==b.G.o||b.G.o!=b.pa+c.length))return!1;for(var k=0;k<c.length;k++){var m=c[k].element,l=c[k].Hb,p;b.pa++;Ri(m,b.id);l&&(b.Ka++,p=b.id+"-t",Ri(l,p));var r=b.cb(m,l);M(r)&&b.R.push(r);b.R.push(Si(m,b.id));l&&p&&b.R.push(Si(l,p))}if(b.G.o&&
b.G.o==b.pa||xa)b.S=!0;return!0},Ri=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Si=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Ti=function(a,b){for(var c=wf(a.A)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.D&&!Ui(f))break;d.push(f)}}return d},Ui=function(a){if(xa)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var _cl=function(a,b){rh("CLICK");B(b)};_cl.a="cl";_cl.b=["google"];var Xi,Yi;var hj=function(a){return function(){}},ij=function(a){return function(){}};var sa=function(a,b){var c=b||Ga,d=c.onerror,e=!1;Qh&&!Yh("535.3")&&(e=!e);c.onerror=function(b,c,h,k,m){d&&d(b,c,h,k,m);a({message:b,fileName:c,Pa:h,Yb:k,error:m});return e}};
var Lj=function(a){var b=function(b){b=b||v.event;var c=a.call(this,b);b.returnValue=!1!==c&&(b.returnValue||void 0===b.returnValue);return c};b.gtmOnclickWrapper=!0;return b},_lcl=function(a,b){var c=ra(a,$e,!0),d=ra(a,Ab,!0),e=P(a[af]);0>=e&&(e=2E3);var f=ra(a,Ne,"");rh("LINK_CLICK",!!c,!!d,e,String(f));if(!J.gtmLinkClickListener&&(J.gtmLinkClickListener=!0,!J.addEventListener)){var g=function(a){a=a||v.event;for(var b=Lf(a);b;)b.onclick&&!b.onclick.gtmOnclickWrapper&&(b.onclick=Lj(b.onclick)),
b=b.parentElement};U(J,"mousedown",g,!1);U(J,"keydown",function(a){a=a||v.event;13==a.keyCode&&g(a)},!1)}B(b)};_lcl.a="lcl";_lcl.b=[];var gk=98,hk=[],ik=[],jk=[],kk=new lf,lk=[],Z=[],ph=[],qh=[],mk=function(){this.I=[]};mk.prototype.set=function(a,b){this.I.push([a,b]);return this};mk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.I.length;d++){var e=nk(this.I[d][0],a,b),f=nk(this.I[d][1],a,b);c[e]=f}return c};var ok=function(a){this.index=a};ok.prototype.resolve=function(a,b){var c=jk[this.index];if(c&&!b(c)){var d=c[Uc];if(a){if(a.get(d))return;a.set(d,!0)}c=nk(c,a,b);a&&a.set(d,!1);return mf(c)}};
var _M=function(a){return new ok(a)},pk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=nk(hk[a[f]],b,c);g===Ng&&(e=!0);d.push(g)}return e?new zh(d):d.join("")}},_T=function(a){return new pk(arguments)},qk=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=nk(a[0],c,d);if(a[0]instanceof ok&&b(8)&&b(16)){if(e===Ng)return e;var f=pa();kk.set(f,e);return'google_tag_manager["GTM-K7KZWM"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new qk(arguments)},rk=function(a,b){this.w=a;this.ma=b},_R=function(a,b){return new rk(a,b)},nk=function(a,b,c){var d=a;if(a instanceof ok||a instanceof mk||a instanceof pk||a instanceof qk)return a.resolve(b,c);if(!(a instanceof rk))if(df(a))for(var d=
[],e=0;e<a.length;e++)d[e]=nk(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=nk(a[f],b,c))}return d},sk=function(a,b){var c=b[a],d=c;if(c instanceof ok||c instanceof qk||c instanceof pk||c instanceof rk)d=c;else if(df(c))for(var d=[],e=0;e<c.length;e++)d[e]=sk(c[e],b);else if("object"==typeof c){var d=new mk,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],sk(c[f],b))}return d},uk=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");
0==a&&(e[1]=hk[e[1]]);if(1==a)for(var f=tk(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=ik[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=tk(e[g]);3==a&&(c[d]=hk[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=hk[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},tk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<gk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:
62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},vk=function(a,b,c){a.push.apply(a,uk(b,c))};
var dg=function(){},Dk=function(a){},gg=function(){},Ek=function(a){},Fk=function(a,b){},Gk=function(a,b){},eg=function(a){};var Hk=function(a){var b=this;this.g=a;this.complete=this.Ua=!1;this.la=[];this.fa=[];this.O=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||qf(b.la);uf(b,1);if(Sa[a])for(var e=0;e<Sa[a].length;e++)Sa[a].shift().O()};this.N=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||
qf(b.fa);uf(b,2);if(Sa[a])for(var e=0;e<Sa[a].length;e++)Sa[a].shift().N()};this.B=cf},Ik=function(a,b){a.la.push(b)},Jk=function(a,b){a.fa.push(b)},Kk=function(a){this.J=[];this.Ea=[];this.Ma={};this.va=[];this.U=0;this.Sa={};this.Va={};this.Fa={};this.event=a};Kk.prototype.addListener=function(a){this.va.push(a)};
var Lk=function(a,b,c,d,e,f){if(!c.complete){a.J[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=df(d)?d.slice():["or",d];e=df(e)?e.slice():[e];f=df(f)?f.slice():[f];a.Ma[b]=d;a.Sa[b]=0<e.length;a.Va[b]=0<f.length;a.U++;var g=function(){0<a.U&&a.U--;0<a.U||qf(a.va)};Ik(c,g);Jk(c,g)}},Mk=function(a,b,c){a.J[b]&&(Ik(a.J[b],function(){c(b,!0)}),Jk(a.J[b],function(){c(b,!1)}))},Nk=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof rk&&a[g].w===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Rk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=Ok(h,b,a);if(f=g){var k=Pk(b,!0);0<k.length&&e(k[0].w);c.push(f);var l=Pk(b,!1);0<l.length&&e(l[0].w)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Pk(g.g,!0);if(0<h.length){var k=c[f-1],m=Qk(g);Ik(k,m);0==h[0].ma&&Jk(k,m)}var l=Pk(g.g,!1);0<l.length&&(m=Qk(c[f+1]),Ik(g,m),0==l[0].ma&&Jk(g,m))}a.Ea.push(c)}},Pk=function(a,b){var c=b?ee:ve,d=Z[a],e=void 0===d[c]?[]:d[c];return df(e)?e:[e]},Qk=function(a){return function(){a.B()}},Tk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Pk(a,!0);0<b.length&&f(b[0].w);e.push(a);var c=Pk(a,!1);0<c.length&&f(c[0].w)};
f(d.g);b[d.g]=e}Sk(a,b);return b},Sk=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<gf(b[e],d)){delete b[d];break}}};var Vk=function(a,b){return function(){a[Lc]=b.O;a[Mc]=b.N;var c=b.g,d=b.s&&b.s.Fa[c],e=Ra[c]&&Ra[c].state,f=d?void 0!==d:b.Ua||b.Zb,g=Ra[c]&&Ra[c].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){uf(b,0);var m=b.s?b.s.event:void 0;a=Uk(a,m?m.c:ng());if(m){var l=a;Fk(m,c)}mf(a,b.O,b.N)}else h&&0==e||k&&0==d?Sa[c].push(b):h&&1==e||k&&1==d?b.O():b.N()}},Uk=function(a,b){a=nk(a,new lf,b);return a},Ok=function(a,b,c){var d=new Hk(b);d.s=c;Ik(d,hj(a));Jk(d,ij(a));d.B=Vk(a,d);return d};
var Zk=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=p+b[0];v[m()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!qa(b))return!1;for(var e=ra(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;a[mc]?c=N("ecommerce"):
a[lc]&&(c=a[lc].ecommerce);if(!qa(c))return;c=Object(c);var e=ra(a[Gc],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],
h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&w[e]||!c&&void 0===w[e])){var f=x[e]?ma(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}O("GoogleAnalyticsObject",a[td]||"ga",!1);var m=function(){return v.GoogleAnalyticsObject},l=O(m(),function(){var a=v[m()];a.q=a.q||[];a.q.push(arguments)},!1);l.l=Number(G());var p="",r="";"string"!=typeof a[Ie]?(r=pa(),p=r+"."):""!==
a[Ie]&&(r=a[Ie],p=r+".");var u=!1;
var z={name:r};l("create",a[Ua],z);d("set","&gtm","GTM-K7KZWM");e("nonInteraction",yd);var H;a[ed]&&d("require","linkid","linkid.js");d("set","hitCallback",function(){if(M(a[Nc]))a[Nc]();else{var c=a[Gc],d=c&&c.hitCallback;M(d)&&d()}b()});if(a[Ee]){a[vc]&&(d("require","ec","ec.js"),h());var F={hitType:"event",eventCategory:String(a[zc]),eventAction:String(a[yc]),eventLabel:f(String,a[Ac]),eventValue:f(P,a[Bc])};k(H,F,!1);d("send",F);}else if(a[Fe]){}else if(a[He]){}else if(a[Ge]){}else if(a[cc]){}else if(a[ac]){}else if(a[De]){}else{a[vc]&&(d("require","ec","ec.js"),h());if(a[kc]&&!a[xc]){var Q="_dc_gtm_"+String(a[Ua]).replace(/[^A-Za-z0-9-]/g,"");d("require","displayfeatures",void 0,{cookieName:Q})}H?d("send","pageview",H):d("send","pageview");}if(!Zk){var V=a[Zb]?"u/analytics_debug.js":"analytics.js";a[Vc]&&!a[Zb]&&(V="internal/"+V);
Zk=!0;q(I("https:","http:","//www.google-analytics.com/"+V,u),function(){v[m()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var $k,al;var jl=!1;var kl=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=lk[b]&&nk(lk[b],new lf,c),e=d;if(d)if(d[db]&&df(d[R]))for(var f=d[R],e=!1,g=0;!e&&g<f.length;g++)d[R]=f[g],e=mf(d);else e=mf(d);a[b]=[e,d]}return a[b]}},Ck=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.M(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.M(e[d],a.c)[0])return!1;return!0},ll=!1,Zf=function(a,b,c,d){switch(b){case "gtm.js":if(ll)return!1;ll=!0;break;case "gtm.sync":if(N("gtm.snippet")!=Oa)return!1}N("tagTypeBlacklist");
for(var e={id:a,name:b,ba:c||cf,aa:tk(),ka:tk(),M:kl(),c:ng()},f=[],g=0;g<ph.length;g++)if(Ck(e,ph[g])){f[g]=!0;for(var h=e,k=ph[g],m=k[1],l=0;l<m.length;l++)h.aa[m[l]]=!0;for(var p=k[3],l=0;l<p.length;l++)h.ka[p[l]]=!0}else f[g]=!1;Fk(e);var u=[];for(var w=0;w<gk;w++)if(e.aa[w]&&!e.ka[w])if(e.c(Z[w])){}else{u[w]=Z[w];}e.P=u;for(var x=new Kk(e),z=0;z<gk;z++)if(e.aa[z]&&!e.ka[z])if(e.c(Z[z])){}else{var E=e.P[z],H=Ok(E,z,x);Lk(x,z,H,E[fc],E[ee],E[ve]);if(E[Ta])break}x.addListener(e.ba);for(var F=[],
y=0;y<x.J.length;y++){var K=x.J[y];if(K){var A=x.Ma[y],C=x.Sa[y],L=x.Va[y];if(0!=A.length||C||L){if(0<A.length)for(var T=Nk(A,K.B),Q=0;Q<A.length;Q++)A[Q]instanceof rk&&A[Q].w!=y&&Mk(x,A[Q].w,T);(C||L)&&Rk(x,y)}else F.push(y)}}for(y=0;y<F.length;y++)x.J[F[y]].B();for(y=0;y<x.Ea.length;y++){for(var va=x.Ea[y],V=va,la=[],ha=0;ha<V.length;ha++){var pb=V[ha],nb=pb.g,Mb=Ra[nb],qd=Mb.firingOption;0!=qd&&(1==qd&&void 0!==pb.s.Fa[nb]||2==qd&&void 0!==Mb.state)&&la.push(pb)}var rd=Tk(la),uc=void 0;for(uc in rd)if(rd.hasOwnProperty(uc)){for(var xf=
void 0,oj=void 0,nd=rd[uc],zl=nd[0],vj=nd[nd.length-1],wj,Ia=0;Ia<V.length;Ia++){var od=V[Ia];!xf&&od.g==zl&&0<Ia&&(xf=V[Ia-1]);od.g==vj&&Ia<V.length-1&&(oj=V[Ia+1]);if(-1<gf(nd,od.g))if(wj=V.splice(Ia,1)[0],od.g==vj)break;else Ia--}if(wj){var xj=Number(uc),na=xf,yf=oj;if(na){var Al=na.la[0],Bl=na.fa[0],yj=na;yj.la=[];yj.fa=[];Ik(na,Al);Jk(na,Bl)}if(na&&yf){var zf=Qk(yf);Ik(na,zf);var Af=Pk(na.g,!1);0<Af.length&&Af[0].w!=xj&&0==Af[0].ma&&Jk(na,zf);var Bf=Pk(yf.g,!0);0<Bf.length&&Bf[0].w!=xj&&0==Bf[0].ma&&
Jk(na,zf)}}}0<va.length&&va[0].B()}0<x.U||qf(x.va);d&&M(d)&&d({passingRules:f,resolvedTags:e.P});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var Bj in e.P)if(e.P.hasOwnProperty(Bj)){var Cj=e.P[Bj],Cf;if(!(Cf=void 0==Cj[Uc])){var Dj=Cj[Uc];Cf=!("function"!=typeof String.prototype.startsWith?0===Dj.indexOf("_implicit"):Dj.startsWith("_implicit"))}if(Cf)return!0}return!1};var ml={macro:function(a){if(kk.contains(a))return kk.get(a)}};ml.dataLayer=Vf;ml.onHtmlSuccess=Ch(!0);ml.onHtmlFailure=Ch(!1);ml.callback=function(a){Da.hasOwnProperty(a)&&M(Da[a])&&Da[a]();delete Da[a]};ml.ib=function(){var a=v.google_tag_manager;a||(a=v.google_tag_manager={});a["GTM-K7KZWM"]||(a["GTM-K7KZWM"]=ml);ua=a};(function(){var a=function(a){var b=O("google_tag_manager",{},!1),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};ah=a("linkClickMap");bh=a("formSubmitMap")})();
hk.push.apply(hk,function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','1687147_2147479553',_ua,true,'UA-35925761-10',false,'\x26tid',{10:8},1,'modal-load','1687147_1',_u,'Page URL',_M(1),'Modal open','\x26t','\x26ec','\x26ea','\x26ni','event',{10:8,19:23,20:17,21:18,22:9},2,'modal-dismiss','Modal close','1687147_2',{10:8,19:23,20:17,21:27,22:9},3,_cn,_v,'Click Classes','gtm.elementClasses',_M(2),'cta-btn','gtm.click','1687147_11','Modal conversion',{10:8,19:23,20:17,21:39,22:9},4,'Click URL','gtm.elementUrl',_M(3),'rjmetrics.com','blog','demo','gtm.linkClick',_re,'_triggers','gtm.triggers','',_M(4),'(^$|((^|,)1687147_4($|,)))','1687147_4','tumblr','1687147_7','referral to rjmetrics','\x26el',{10:8,19:23,20:17,21:58,59:44,22:9},5,'1687147_5','referral to blog',{10:8,19:23,20:17,21:63,59:44,22:9},6,'rjmetrics','utm','.','1687147_6','referral to microsite','Click Element','gtm.element',_M(5),{10:8,19:23,20:17,21:70,59:73,22:9},7,'1687147_12',_cl,9,'1687147_13',_lcl,'2000',10,'1687147_14',11,'1687147_15',12,'1687147_16',13,'1687147_17',14,_html,'\n\x3cscript type\x3d\x22text/gtmscript\x22\x3e(function(a,c,e,f,d,b){a.hj\x3da.hj||function(){(a.hj.q\x3da.hj.q||[]).push(arguments)};a._hjSettings\x3d{hjid:98503,hjsv:5};d\x3dc.getElementsByTagName(\x22head\x22)[0];b\x3dc.createElement(\x22script\x22);b.async\x3d1;b.src\x3de+a._hjSettings.hjid+f+a._hjSettings.hjsv;d.appendChild(b)})(window,document,\x22//static.hotjar.com/c/hotjar-\x22,\x22.js?sv\\x3d\x22);\x3c/script\x3e',8,'Page Hostname','host','Page Path','path',_f,'Referrer','Event','Click ID','gtm.elementId','Click Target','gtm.elementTarget'],b=[],c=0;c<a.length;c++)b[c]=sk(c,a);return b}());vk(ik,0,"17:0,17:1,19:2,3:3,4:4,17:6,23:7,0:8,13:9,12:9,27:9,8:9,9:9,1:11,20:9,11:9,24:12,4:13,25:7,2:7,17:15,19:16,15:17,14:18,22:9,1:24,24:25,4:26,14:27,1:29,24:30,17:31,17:32,19:33,21:34,3:35,4:36,4:37,14:39,1:40,24:41,19:42,21:43,3:44,4:45,4:46,4:47,4:48,17:49,19:50,21:51,10:52,7:25,3:53,4:54,4:56,14:58,16:44,1:60,24:61,14:63,1:64,24:65,4:66,4:67,4:68,14:70,19:71,21:72,16:73,1:74,24:75,17:77,24:78,17:80,28:9,5:9,26:55,29:81,24:82,24:84,24:86,24:88,24:90,17:91,18:92,24:93,19:94,6:95,19:96,6:97,17:98,19:99,19:100,19:101,21:102,19:103,21:104");vk(jk,1,"G,AAAM,AAAAAc,AAAAAEgB,AAAAAEAAe,AAAAAEAAAAAG,AAAEAAAAAAAAAAY,AAAEAAAAAAAAAAgB,AAAAAAAAAAAAAAAG,CAAAAAAAAAAAAAAI,AAAAAEAAAAAAAAAw,AAAAAEAAAAAAAAAAD");vk(lk,1,"Z,JAg,JAAAI,AAAAAiB,JAAAAAC,AAAAACAG,AAAAACAK,AAAAACAS,JAAAAAAg,AAAAAAAAhB,AAAAACACAC,AAAAACACAAI,AAAAACACAAQ,AAAAACACAAg");vk(Z,1,"g_f,gvMzH,gvMTxB,gvMTBAc,gvMTBAAAA8,gvMTBAAAAIH,gvMTBAAAAAA5,AAAAAAAAAAAAD,AAAAAAAAAAAA8D,AAAAAAAAAAAABE,AAAAAAAAAAAABI,AAAAAAAAAAAABQ,AAAAAAAAAAAABg,ABAAAAAAAAAAAAH");vk(ph,2,"B:B-D::,C:C::,E:E::,Y:I::,gM:Q:AD:,QQ:Q::,QB:g::,QAD:AB:Ag:");vk(qh,4,"5.76.79.83.85.87.89.5:,14:,28:,38:,55:,57:,62:,69:");for(var nl=0;nl<Z.length;nl++){var ol=Z[nl],pl=1;ol[Ad]?pl=2:ol[Oe]&&(pl=0);Ra[nl]={firingOption:pl,state:void 0};Sa[nl]=[]}ml.ib();
(function(a){})("async");
(function(){var a=O("dataLayer",[],!1),b=O("google_tag_manager",{},!1),b=b["dataLayer"]=b["dataLayer"]||{};ya.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Of.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for($f.push.apply($f,b);300<this.length;)this.shift();return hg()};$f.push.apply($f,a.slice(0));B(ig)})();var xl=v;
if("interactive"==J.readyState&&!J.createEventObject||"complete"==J.readyState)Gf();else{U(J,"DOMContentLoaded",Gf);U(J,"readystatechange",Gf);if(J.createEventObject&&J.documentElement.doScroll){var yl=!0;try{yl=!xl.frameElement}catch(a){}yl&&If()}U(xl,"load",Gf)}"complete"===J.readyState?Pf():U(v,"load",Pf);
(function(a){})("async");(function(){})();var _vs="res_ts:1465845900774000,srv_cl:134327197,ds:live,cv:16";
})()
